FROM golang:alpine

WORKDIR /app

# Install air for hot-reloading
RUN go install github.com/air-verse/air@latest

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Expose port 8080
EXPOSE 8080

# Command to run air
CMD ["air", "-c", ".air.toml"]
